### ISSUE TITLE
Change BeanReader and BeanWriter to implements Closeable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [beanio/beanio#126]
```
So we can use try-with-resources feature to auto close resources.
```

Original issue reported on code.google.com by `ota...@otavio.com.br` on 1 Nov 2014 at 9:12

**Comment by bjansen** [comment]
This has been fixed in 73b1266a5adf222f899af4429e75ea8679043800.
`BeanWriter extends AutoCloseable` and `BeanReader extends Closeable`.
