### ISSUE TITLE
JavaSE 8 - LocalDate & LocalTime Support

### ISSUE THREAD

**Issue by nicwillemse** [beanio/beanio#132]
It would be great if the library had support for LocalDate and LocalTime that was introduced with JavaSE 8

**Comment by garcia-jj** [comment]
Hello @bjansen. I have java.time handlers in a personal project mine, so I can contribute if you want. Please, let me know if this issue still need some love, and I can work on this.

Thank U

**Comment by bjansen** [comment]
@garcia-jj here's what I have so far: https://github.com/beanio/beanio/blob/33e3461b28c1b7be14edd5c5fddd3b219cc9ada9/src/org/beanio/types/TemporalAccessorTypeHandler.java

If you have time to test this branch and perhaps compare the implementation with yours, that would be great!

**Comment by bjansen** [comment]
Fixed by #144
