### ISSUE TITLE
Automatic-Module-Name

### ISSUE THREAD

**Issue by bjansen** [beanio/beanio#138]
Provide an `Automatic-Module-Name` in `MANIFEST.MF` to suggest a Jigsaw module name for projects that use JDK9+.

**Comment by krisbanas** [comment]
Hi @bjansen, can I take this issue? 
I just need to know what name you want to use. I'd suggest simply going with `beanio` - is it OK?

**Comment by bjansen** [comment]
The [general](https://stackoverflow.com/questions/43192741/how-should-i-name-my-java-9-module) [consensus](https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html) regarding module names is to use reverse-DNS names. I'd prefer having `com.github.beanio` instead.

**Comment by krisbanas** [comment]
PR ready for review!
