### ISSUE TITLE
@Field annotation don't have ignore  property

### ISSUE THREAD

**Issue by bozoh** [beanio/beanio#149]
The @Field annotation don't have ignore  property

lib version 3.0.0.M1

![image](https://user-images.githubusercontent.com/2317639/210667974-b809b629-77f4-489d-8aa8-504bdc2d7144.png)

**Comment by bjansen** [comment]
Why should it have this property?

**Comment by bjansen** [comment]
Closing, as the expectation is not clear. Feel free to reopen.
