### ISSUE TITLE
BEANIO: Cannot invoke "java.text.DecimalFormat.format(Object)" because the return value of "java.lang.ThreadLocal.get()" is null

### ISSUE THREAD

**Issue by msaravanan89** [beanio/beanio#166]
### Discussed in https://github.com/beanio/beanio/discussions/165

<div type='discussions-op-text'>

<sup>Originally posted by **msaravanan89** September  5, 2024</sup>
Hi team, Thanks in advance!!

I am migrating my code from beanio 2.1.0 to beanio to 3.0.0. 

i am getting this error. "**java.lang.NullPointerException: Cannot invoke "java.text.DecimalFormat.format(Object)" because the return value of "java.lang.ThreadLocal.get()" is null
	at org.beanio.types.NumberTypeHandler.format(NumberTypeHandler.java:158)
	at com.asc.udcs.util.TypeConverterUtil.format(TypeConverterUtil.java:64)**".  

How to resolve it? Below is my calling class(**TypeConverterUtil.java)** 

package com.asc.udcs.util;

import java.math.BigInteger;

import org.beanio.internal.util.TypeHandlerFactory;
import org.beanio.types.DateTypeHandler;
import org.beanio.types.NumberTypeHandler;
import org.beanio.types.TypeConversionException;
import org.beanio.types.TypeHandler;

public final class TypeConverterUtil {
	
	private TypeConverterUtil() {
	}
	
	@SuppressWarnings("unchecked")
	public static <T extends Object> T convert(Object value, Class<T> type, String format) throws TypeConversionException {
		
		if (value == null) {
			return null;
		}
		
		if ((type == null || type.isInstance(value))) {
			return (T) value;
		}
		
		if ((BigInteger.class.isAssignableFrom(type) || Integer.class.isAssignableFrom(type)) && format == null) {
			format = "############";
		}
		
		TypeHandler handler = TypeHandlerFactory.getDefault().getTypeHandlerFor(type);
		if (handler instanceof NumberTypeHandler typeHandler) {
			typeHandler.setPattern(format);
		}
		
		if (handler instanceof DateTypeHandler typeHandler) {
			typeHandler.setPattern(format);
		}
		
		if (handler != null) {
			return (T) handler.parse(format(value, value.getClass(), format));
		}
		return (T) value;
	}

	public static String format(Object value, Class<?> type, String format) throws TypeConversionException {
		
		if (value == null) {
			return null;
		}
		if (type == null) {
			return value.toString();
		}
		TypeHandler handler = TypeHandlerFactory.getDefault().getTypeHandlerFor(type);
		if (handler == null) {
			return value.toString();
		}
		if (handler instanceof NumberTypeHandler typeHandler) {
			typeHandler.setPattern(format);
		}
		if (type.isInstance(value)) {
			return handler.format(value);
		}
		return handler.format(handler.parse(value.toString()));
	}
	
}

</div>

**Comment by bjansen** [comment]
Hi, this looks like #163, which was fixed in a previous version. Could you try updating your dependency to version 3.1.0?

**Comment by msaravanan89** [comment]
Hi, thanks. as per you comment. After updated to version 3.1.0 issue resolved.
